ai:
    api_key: xxxxxx
    base_url: https://api.deepseek.com/v1
    model: deepseek-chat
    provider: openai
git:
    amend: false
    diff_unified: 3
    exclude_list:
        - go.sum
proxy:
    skip_verify: true
